apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgenai-frontend
  namespace: webgenai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgenai-frontend
  template:
    metadata:
      labels:
        app: webgenai-frontend
    spec:
      containers:
        - name: webgenai-frontend
          image: sagar/webgenai-frontend@sha256:2e94f1a6fa028f34d3405974fe52c17de9bae5712ec2219ef5652a08ab3953a9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webgenai-frontend
  namespace: webgenai-core
spec:
  type: ClusterIP
  selector:
    app: webgenai-frontend
  ports:
    - port: 80
      targetPort: 80